Apex/Assignment 5/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Attendee_Name__c</fullName>
        <formula>Contact__r.FirstName  &amp;&quot; &quot;&amp;  Contact__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attendee Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Field is to setup relationship between the attendee and contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_Session__c</fullName>
        <label>Training Session</label>
        <referenceTo>Training_Session__c</referenceTo>
        <relationshipLabel>Attendees (Training Session 1)</relationshipLabel>
        <relationshipName>Attendees1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>AT-{000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Apex/Integration/Assignment 1/src/objects/Contact.object
<CustomObject>
</CustomObject>

Apex/Assignment 5/objects/Contact.object
    <fields>
        <fullName>Number_of_training_sessions__c</fullName>
        <label>Number of training sessions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

Apex/Assignment 5/objects/Training_Session__c.object
<CustomObject>
    <label>Training Session</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Apex/Assignment 7/src/classes/AttendeeTriggerHandler.cls
/*
* Purpose          :   Handler Class of Trigger on Attendee__c object
* 
* Created by       :   Mukul Pichunia
* 
* Created Date     :   08-12-2024
* 
* Revision Logs    :   V_1.0 - Created
*/
public without sharing class AttendeeTriggerHandler {
    /*
	 * Method Name  :   handleAttendeeInsertUpdateAndDelete
	 * 
	 * Created by   :   Mukul Pichunia
	 * 
	 * Purpose      :   Create a set of contact ids
	 * 
	 * @return      :   void
	 * 
	 * @params      :   List<Attendee__c> newListOfAttendee, Map<Id, Attendee__c> mapOfOldAttendies 
	 * 
	 */
    public static void handleAttendeeInsertUpdateAndDelete(List<Attendee__c> newList, Map<Id, Attendee__c> oldMap) {
        
        Set<Id> contactIds = new Set<Id>();
        if (newList != null || oldMap != null) {
            
            for (Attendee__c att : newList != null ? newList : oldMap.values()) {
                
                if (att.Contact__c != null) {
                    contactIds.add(att.Contact__c);
                }
                if (oldMap != null && oldMap.get(att.Id).Contact__c != null && att.Contact__c != oldMap.get(att.Id).Contact__c) {
                    contactIds.add(oldMap.get(att.Id).Contact__c);
                }
            }
        }
        if (!contactIds.isEmpty()) {
            updateContact(contactIds);
        }
    }
    
    /*
	 * Method Name  :   updateContact
	 * 
	 * Created by   :   Mukul Pichunia
	 * 
	 * Purpose      :   Updates the 'No. Of Attended Training Session' field on the Contact object according to the number of sessions that the contact is enrolled in.
	 * 
	 * @return      :   void
	 * 
	 * @params      :   Set<Id> contactIds
	 * 
	 */
    public static void updateContact(Set<Id> contactIds) {
        
        Map<Id, Set<Id>> contactTrainingSessionMap = new Map<Id, Set<Id>>();
        List<Contact> contactsToUpdate = new List<Contact>();
        
        // This Query Provide List of attendees where contact__c value matches contact id in set
        List<Attendee__c> existingList = [SELECT Id, Attendee_Name__c, Contact__c, Training_Session__c 
                                          FROM Attendee__c 
                                          WHERE Contact__c IN :contactIds];
        
        
        if (!existingList.isEmpty()) {
           
            for (Attendee__c att : existingList) {
                if (att.Contact__c != null) {
                    if (!contactTrainingSessionMap.containsKey(att.Contact__c)) {
                        contactTrainingSessionMap.put(att.Contact__c, new Set<Id>());
                    }
                    contactTrainingSessionMap.get(att.Contact__c).add(att.Training_Session__c);
                }
            }
        }
        
        
        for (Id notAvail : contactIds) {
            
            if (!contactTrainingSessionMap.containsKey(notAvail)) {
                Contact cont = new Contact(
                    Id = notAvail,
                    Number_of_training_sessions__c = 0
                );
                contactsToUpdate.add(cont);
            } 
        }
        for (Id contactId : contactTrainingSessionMap.keySet()) {
            
            Contact cont = new Contact(
                Id = contactId,
                Number_of_training_sessions__c = contactTrainingSessionMap.get(contactId).size()
            );
            contactsToUpdate.add(cont);
        }
        
        // Performing the update if there are contacts to update
        if (!contactsToUpdate.isEmpty()) {
            update contactsToUpdate;
        }
        
    }
}