Lecture 3/src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Apex/Assignment 1/src/objects/School__c.object
<CustomObject>
    <fields>
        <fullName>NumberOfStudents__c</fullName>
        <description>This field contains total number of students in school updated by apex code</description>
        <label>NumberOfStudents</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

Lecture 3/src/objects/School__c.object
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>

Apex/Assignment 1/src/classes/SchoolManager.cls
public with sharing class SchoolManager {
    public SchoolManager() {}
    public void updateNumberOfStudentsDetails(String schoolName) {

        School__c fetchedSchool  = [Select Id from School__c where School__c.Name = :schoolName];

        if (fetchedSchool.Active__c) {

            List<Class__c> classList = [Select Id from Class__c where School__r.Id = :fetchedSchool.id];

            if (classList.isEmpty()) {

                fetchedSchool.Active__c = false;

            } else {

                Set<Id> classSet = new Set<Id>();

                for (Class__c cls: classList) {

                    classSet.add(cls.Id);

                }
                List<AggregateResult> aggregateList = [Select Count(id) totalStudents, Class__r.Id classId 
                                                        from Student__c where Class__r.id IN :classSet 
                                                        group by Class__r.id];
                Integer totalStudents = 0;                                        
                For (AggregateResult ar :  aggregateList) {
                    totalStudents += (Integer) ar.get('totalStudents');
                   // System.debug('Class ID: ' + ar.get('classId') + ', Student Count: ' + ar.get('totalStudents'));

                }
                fetchedSchool.NumberOfStudents__c = totalStudents;
            }
            update fetchedSchool;
            System.debug('Updated school: ' + fetchedSchool);
        } else {
            System.debug('School not found');
        }

    }
}