Lecture 3/src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Apex/Assignment 1/src/objects/School__c.object
<CustomObject>
</CustomObject>

Lecture 3/src/objects/Student2__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students2</relationshipLabel>
        <relationshipName>Students2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student2</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Student2 ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students2</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Apex/Assignment 1/src/classes/DynamicCollections.cls
public class DynamicCollections {
    Map<String, Map<String, List<Student2__c>>> mapOfSchoolNameWithClassNameAndRelatedStudentsDetails;
    public DynamicCollections() {
        mapOfSchoolNameWithClassNameAndRelatedStudentsDetails = new  Map<String, Map<String, List<Student2__c>>>();
        for (Student2__c st : [Select Name, Id,Class__c, Class__r.name,Class__r.School__c,Class__r.School__r.Name 
                               from Student2__c 
                               where Class__c != null
                               And Class__r.School__c != null
                              ]) 
        {
            if (mapOfSchoolNameWithClassNameAndRelatedStudentsDetails.containsKey(st.Class__r.School__r.Name)) {
                if (mapOfSchoolNameWithClassNameAndRelatedStudentsDetails.get(st.Class__r.School__r.Name)
                    .containsKey(st.Class__r.Name)) {
                    mapOfSchoolNameWithClassNameAndRelatedStudentsDetails.get(st.Class__r.School__r.Name).get(st.Class__r.Name)
                        .add(st);
                }  
                else {
                    mapOfSchoolNameWithClassNameAndRelatedStudentsDetails.get(st.Class__r.School__r.Name)
                        .put(st.Class__r.Name, new List<Student2__c> {st});
                }
                
            } else {
                Map<String, List<Student2__c>> mapClassNameWithStudents = new Map<String, List<Student2__c>>();
                if (!mapClassNameWithStudents.containsKey(st.Class__r.name)) {
                    mapClassNameWithStudents.put(st.class__r.Name, new List<Student2__c>());
                }
                mapClassNameWithStudents.get(st.Class__r.Name).add(st);
                mapOfSchoolNameWithClassNameAndRelatedStudentsDetails.put(st.Class__r.School__r.Name, mapClassNameWithStudents);
            }
        }
        
        System.debug('@@@@@@ map ' + mapOfSchoolNameWithClassNameAndRelatedStudentsDetails);
    }
}


//{Active Test={Class 12=(Student2__c:{Name=ST-0003, Id=a0NdM000009w5TZUAY, Class__c=a0DdM00000FUqqjUAD})}, 
//Kendriya Vidyalaya Number 5={Class 1=(Student2__c:{Name=ST-0001, Id=a0NdM000007zE6rUAE, Class__c=a0DdM00000Edip9UAB}), Class 2=(Student2__c:{Name=ST-0002, Id=a0NdM000009K4iDUAS, Class__c=a0DdM00000FKLxbUAH})}, 
//MyDream={clasee 33=(Student2__c:{Name=ST-0004, Id=a0NdM000009w6KnUAI, Class__c=a0DdM00000FMktBUAT})}}